-- CATEGORIES
INSERT INTO CATEGORIES (name, description) VALUES
                                                   ('Renaissance', 'A period of European history marking the transition from the Middle Ages to modernity, characterized by developments in art, architecture, politics, science, and literature.'),
                                                   ('Post-Impressionism', 'A predominantly French art movement that developed roughly between 1886 and 1905, led by Paul Cézanne, Paul Gauguin, Vincent van Gogh, and Georges Seurat.'),
                                                   ('Surrealism', 'A 20th-century avant-garde movement in art and literature that sought to release the creative potential of the unconscious mind, for example by the irrational juxtaposition of images.'),
                                                   ('Baroque', 'A highly ornate and often extravagant style of architecture, art and music that flourished in Europe from the early 17th until the mid-18th century.'),
                                                   ('Cubism', 'An early 20th-century avant-garde art movement that revolutionized European painting and sculpture, and inspired related movements in music, literature, and architecture.');

-- ARTISTS
INSERT INTO ARTISTS (name, description, image_path) VALUES
                                                            ('Leonardo da Vinci', 'Italian polymath of the Renaissance, known for his works such as the Mona Lisa and The Last Supper.', 'https://2.bp.blogspot.com/-3wvH7QnZDk8/TspIn0RnMYI/AAAAAAAACIs/oNLqmHZs2l8/s1600/Leonardo+da+Vinci+I.jpg'),
                                                            ('Vincent van Gogh', 'Dutch post-impressionist painter, famous for his works like Starry Night and Sunflowers.', 'https://th.bing.com/th/id/OIP.d_WS7DSA-u2gjjdV-LqM6QHaJX?rs=1&pid=ImgDetMain'),
                                                            ('Salvador Dalí', 'Spanish surrealist artist, known for his eccentric and imaginative works including The Persistence of Memory.', 'https://th.bing.com/th/id/R.7540ac940f6e7989cf423c036b6005a4?rik=%2bDWwvKcHlp3Aqw&pid=ImgRaw&r=0'),
                                                            ('Rembrandt van Rijn', 'Dutch Golden Age painter, renowned for his portraits and use of light and shadow.', 'https://www.metmuseum.org/toah/images/hb/hb_14.40.618_av1.jpg'),
                                                            ('Pablo Picasso', 'Spanish painter and sculptor, one of the most influential artists of the 20th century, co-founder of Cubism.', 'https://th.bing.com/th/id/OIP.6ZNDNR0-L_QtCn6fFa-tQQHaHa?rs=1&pid=ImgDetMain'),
                                                            ('Claude Monet', 'French painter, a founder of French Impressionist painting, known for his series of Water Lilies.', 'https://th.bing.com/th/id/R.2d251a742c502ce346428f0a0df82506?rik=brvrP%2b20OS8Q3A&riu=http%3a%2f%2fupload.wikimedia.org%2fwikipedia%2fcommons%2f3%2f33%2fClaude_Monet_1899_Nadar.jpg&ehk=h%2b9I5vZ1RIIIsKzmkZnCocVwOtXX%2bO%2fQ2xniZ4EWP7I%3d&risl=&pid=ImgRaw&r=0'),
                                                            ('Michelangelo', 'Italian sculptor, painter, and architect, famous for his works such as the Sistine Chapel ceiling and the statue of David.', 'https://static.wixstatic.com/media/ec6088_7ad05362ccf247f285788cfc380ad0c1~mv2.jpg/v1/fit/w_776%2Ch_1000%2Cal_c%2Cq_80/file.jpg'),
                                                            ('Edgar Degas', 'French artist famous for his paintings, sculptures, prints, and drawings, especially known for his depictions of dancers.', 'https://th.bing.com/th/id/OIP.9QqPErwY21AyhgwMn__sGwHaJ4?rs=1&pid=ImgDetMain'),
                                                            ('Johannes Vermeer', 'Dutch Baroque painter, best known for his genre scenes and use of light, such as in Girl with a Pearl Earring.', 'https://www.thefamouspeople.com/profiles/images/johannes-vermeer-1.jpg'),
                                                            ('Paul Cézanne', 'French artist and Post-Impressionist painter whose work laid the foundations for the transition from 19th-century to 20th-century art.', 'https://th.bing.com/th/id/OIP.N4mZEJFXds3ckXQEjOFxUAHaHa?rs=1&pid=ImgDetMain');


INSERT INTO ART_PIECES (title, artist_id, category_id, image_path, price,description) VALUES
                                    ('Mona Lisa', 1, 1, 'https://th.bing.com/th/id/OIP.LNIjQz_P34Cy8AeGYi1c5gHaLC?rs=1&pid=ImgDetMain', 4.00, 'The Mona Lisa is a half-length portrait painting by Italian artist Leonardo da Vinci. It has been acclaimed as "the best known, the most visited, the most written about, the most sung about, the most parodied work of art in the world."'),
                                    ('Starry Night', 2, 2, 'https://th.bing.com/th/id/R.650d8cb12dee918ea0a3c886eb0a4212?rik=sQp1dIbNSWXfrg&pid=ImgRaw&r=0', 2.00, 'Starry Night is one of the most recognized paintings in the history of Western culture. It depicts the view outside Van Gogh''s sanatorium room window at Saint-Rémy-de-Provence.'),
                                    ('The Persistence of Memory', 3, 3, 'https://upload.wikimedia.org/wikipedia/en/d/dd/The_Persistence_of_Memory.jpg', 3.00, 'The Persistence of Memory is one of Salvador Dalí''s most famous paintings. It features melting clocks draped over various objects in a landscape.'),
                                    ('The Night Watch', 4, 4, 'https://fisunguner.com/wp-content/uploads/2019/02/Rembrandt_Night-Watch.jpg', 5.00, 'The Night Watch is one of the most famous Dutch Golden Age paintings. It depicts a city guard moving out, led by Captain Frans Banning Cocq and his lieutenant, Willem van Ruytenburch.'),
                                    ('Guernica', 5, 5, 'https://upload.wikimedia.org/wikipedia/en/7/74/PicassoGuernica.jpg', 2.00, 'Guernica is a large mural painting by Pablo Picasso. It is one of his most famous works and is regarded by many art critics as one of the most powerful anti-war paintings in history.'),
                                    ('Water Lilies', 6, 2, 'https://th.bing.com/th/id/R.464c8bf9600b29660191e9a8d8118230?rik=IUzw5FlHtmVUuQ&riu=http%3a%2f%2fuploads7.wikiart.org%2fimages%2fclaude-monet%2fwater-lilies-14.jpg&ehk=ZG%2bSuKEZ%2f6C4lzWcbeeNLzXUfHlHNc8x6epPSpy3nvk%3d&risl=&pid=ImgRaw&r=0', 5.00, 'Water Lilies is a series of approximately 250 oil paintings by Claude Monet. They depict Monet''s flower garden at his home in Giverny, and were the main focus of his artistic production during the last thirty years of his life.'),
                                    ('David', 7, 1, 'https://www.gannett-cdn.com/presto/2019/09/07/PCIN/cffb4ebe-98d7-4453-872e-f665bbaf2a8a-the-david.jpg?crop=1919,1080,x0,y0&width=1919&height=1080&format=pjpg&auto=webp', 3.00, 'David is a masterpiece of Renaissance sculpture created by Michelangelo. It depicts the Biblical hero David, represented as a standing male nude.'),
                                    ('The Ballet Class', 8, 2, 'https://artsandculture.google.com/asset/the-ballet-class/fwE5p5FTjV9Ezg?hl=en-GB&ms=%7B%22x%22%3A0.5%2C%22y%22%3A0.5%2C%22z%22%3A9.391335759471355%2C%22size%22%3A%7B%22width%22%3A2.942136829725905%2C%22height%22%3A1.2375000000000003%7D%7D', 4.00, 'The Ballet Class, also known as The Dance Class, is a painting by French impressionist Edgar Degas. It depicts a scene of a ballet class.'),
                                    ('Girl with a Pearl Earring', 9, 4, 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Meisje_met_de_parel.jpg', 1.00, 'Girl with a Pearl Earring is one of Johannes Vermeer''s most famous paintings. It depicts a girl wearing an exotic dress, an oriental turban, and a large pearl earring.'),
                                    ('The Card Players', 10, 5, 'https://paintingandframe.com/art-imgs/paul_cezanne/the_card_players_c_1890-28208.jpg', 4.00, 'The Card Players is a series of oil paintings by French Post-Impressionist artist Paul Cézanne. The series depicts Provencal peasants immersed in their pipe-smoking card games.'),
                                    ('The Last Supper', 1, 1, 'https://i.pinimg.com/originals/74/04/5f/74045f1f5e00d3b3d4def19aad29ab16.jpg', 2.00, 'The Last Supper is a late 15th-century mural painting by Leonardo da Vinci. It portrays the scene of the Last Supper of Jesus with his apostles, as it is told in the Gospel of John.'),
                                    ('The Elephants', 3, 3, 'https://th.bing.com/th/id/OIP.w1GMmRdwRhvzj36RGHmvyQHaF7?rs=1&pid=ImgDetMain', 3.00, 'The Elephants is a painting by the Spanish surrealist artist Salvador Dalí. It features two elephants with elongated legs, one with obelisks on its back, and is often interpreted as a surrealist interpretation of time and space.'),
                                    ('Self-Portrait with Two Circles', 4, 4, 'https://i.redd.it/vhm4yohwpi441.jpg', 1.00, 'Self-Portrait with Two Circles is a painting by the Dutch artist Rembrandt. It is one of over 40 painted self-portraits by Rembrandt, and it is notable for its innovative composition and the presence of two large circles behind the figure, which have been interpreted in various ways.'),
                                    ('Les Demoiselles d’Avignon', 5, 5, 'https://c2.staticflickr.com/6/5085/5352217333_ed393aee68_b.jpg', 1.00, 'Les Demoiselles d’Avignon is a large oil painting created by the Spanish artist Pablo Picasso in 1907. It is considered one of the most important works of art of the 20th century and is widely regarded as a seminal work in the development of modern art.'),
                                    ('Impression Sunrise', 6, 2, 'https://i.pinimg.com/originals/8a/8f/06/8a8f06cb81f70ab84bff94f653cbdfe2.jpg', 4.00, 'Impression, Sunrise is a painting by Claude Monet. It gave its name to the Impressionist movement. The painting is credited with inspiring the name of the Impressionist movement when it was exhibited in 1874 and is one of the most famous works of the movement.'),
                                    ('Sistine Chapel Ceiling', 7, 1, 'https://th.bing.com/th/id/R.c591dfb7ed0461295444703715c35edd?rik=o26xcv3ECjtTkg&pid=ImgRaw&r=0', 2.00, 'The Sistine Chapel ceiling, painted by Michelangelo between 1508 and 1512, is one of the most renowned artworks of the High Renaissance. It depicts nine scenes from the Book of Genesis, including the iconic Creation of Adam.'),
                                    ('L’Absinthe', 8, 2, 'https://www.impressionists.org/images/paintings/labsinthe.jpg', 2.00, 'L’Absinthe is a painting by Edgar Degas depicting a woman sitting in a café with a glass of absinthe in front of her. It is considered one of Degas''s masterpieces and is notable for its realistic portrayal of urban life in late 19th-century Paris.'),
                                    ('The Milkmaid', 9, 4, 'https://th.bing.com/th/id/R.877ea777ee155117116f3b829da99cd3?rik=KOrcKmI5C0GDdA&riu=http%3a%2f%2foldmasters.ie%2fwp-content%2fuploads%2f2017%2f12%2fThe-Milkmaid-by-Vermeer.jpg&ehk=LvyAfO71wfW2p%2fkj1BrxoCQqx7Uy9M8oAdaKURwB7h8%3d&risl=&pid=ImgRaw&r=0', 1.00, 'The Milkmaid is a painting by Johannes Vermeer, known for its exquisite rendering of light and color. It depicts a domestic kitchen scene of a maidservant pouring milk, with intricate details that captivate viewers.'),
                                    ('The Bathers', 10, 5, 'https://th.bing.com/th/id/R.6e8e21707406b334a1fc39ab52527599?rik=jNCmiAu4J%2ba%2fug&pid=ImgRaw&r=0', 6.00, 'The Bathers is a painting by French artist Paul Cézanne. It depicts a scene of several nude women bathing in a natural setting. The painting is notable for its innovative composition and use of color, which were highly influential on later artists.');

INSERT INTO USERS(username, password)
VALUES('admin', '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW');

INSERT INTO USERS(username, password)
VALUES('user', '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW');

INSERT INTO ROLE(name) VALUES ('ROLE_USER');
INSERT INTO ROLE(name) VALUES ('ROLE_ADMIN');

INSERT INTO USER_ROLE(user_id, role_id) VALUES(1, 1);
INSERT INTO USER_ROLE(user_id, role_id) VALUES(1, 2);
INSERT INTO USER_ROLE(user_id, role_id) VALUES(2, 1);